### ISSUE TITLE
WFC3 README not updated on front end

### ISSUE THREAD

**Issue by FDauphin** [spacetelescope/hst_notebooks#313]
The WFC3 REAME was updated in the [repo](https://github.com/spacetelescope/hst_notebooks/blob/main/notebooks/WFC3/README.md) with the new notebook under "Point Spread Function". However, those changes were not reflected on the [front end site](https://spacetelescope.github.io/hst_notebooks/notebooks/WFC3/README.html). Any reasons why?

**Comment by haticekaratay** [comment]
Hello @FDauphin, it appears that the gh-storage has not been updated to reflect changes on the gh-pages. To address this, could you kindly create a ticket for the CI team to investigate? You can visit https://stsci.service-now.com/dmd, select SPB notebook-ci, and create the ticket there. Additionally, please tag me in the ticket so that I can stay informed about the progress. Thank you!

**Comment by FDauphin** [comment]
Issue has been addressed.

**Comment by mgough-970** [comment]
gh-storage branch is only used to store notebooks with generated outputs, readme's etc while they may be there from the initial branch creation are note used.
